### ISSUE TITLE
Add "last updated" timestamp to /about and /data-policy embeds

### ISSUE THREAD

**Issue by ntseng** [Imaginary-Horizons-Productions/BountyBot#262]
`EmbedBuilder.setEmbed()` allows an argument of a Date or number. Setting that Date or number to the release date of the update with which the embed's contents were last updated will provide users greater context for that documentation.

Creating a constant to hold those values or (ideally) a script that updates the values on repo pull or bot startup would be helpful for reducing documentation spoilage.

**Comment by ntseng** [comment]
node fs might be able to look at last updated time of file?

**Comment by SillySalamndr** [comment]
Yes: https://nodejs.org/api/fs.html#fspromisesstatpath-options
